export const AllCompanies = [
  {
    ecmCompanyId: 1,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 2,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 3,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 4,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 5,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 6,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 7,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 8,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 9,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 10,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 11,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 12,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 13,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 14,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 15,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 16,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 17,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 18,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 19,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 20,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 21,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 22,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 23,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 24,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 25,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 26,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 27,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 28,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 29,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 30,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 31,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 32,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 33,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 34,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 35,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 36,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 37,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 38,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 39,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 40,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 41,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 42,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 43,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 44,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 45,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 46,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 47,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 48,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 49,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
  {
    ecmCompanyId: 50,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'akash17@gmail.com',
    ecmCreatedBy: 'string',
    ecmCreatedTs: new Date().toLocaleDateString(),
    ecmUpdatedBy: 'string',
    ecmUpdatedTs: new Date().toLocaleDateString(),
    ecmCompanyFlag: 'Y',
    ebimIndustryName: 'Diversified',
    esmSectorName: 'Diversified',
    esesmSectorName: 'Diversified',
    etmIndustryName: 'Diversified',
  },
];

export const companies = [
  {
    esgCompanyId: 1,
    esgCompanyName: 'Reliance Industries Limited',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 2,
    esgCompanyName: 'Tata Consultancy Services Limited',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 3,
    esgCompanyName: 'HDFC Bank Limited',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 4,
    esgCompanyName: 'ICICI Bank Limited',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 5,
    esgCompanyName: 'Bharti Airtel Limited',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 6,
    esgCompanyName: 'State Bank of India',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 7,
    esgCompanyName: 'Infosys Limited',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 8,
    esgCompanyName: 'Life Insurance Corporation Of India',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 9,
    esgCompanyName: 'ITC Limited',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 10,
    esgCompanyName: 'Hindustan Unilever Limited',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 11,
    esgCompanyName: 'Larsen & Toubro Limited',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 12,
    esgCompanyName: 'Bajaj Finance Limited',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 13,
    esgCompanyName: 'HCL Technologies Limited',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 14,
    esgCompanyName: 'Maruti Suzuki India Limited',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 15,
    esgCompanyName: 'Sun Pharmaceutical Industries Limited',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 16,
    esgCompanyName: 'Adani Enterprises Limited',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 17,
    esgCompanyName: 'Kotak Mahindra Bank Limited',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 18,
    esgCompanyName: 'Titan Company Limited',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 19,
    esgCompanyName: 'Oil & Natural Gas Corporation Limited',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
  {
    esgCompanyId: 20,
    esgCompanyName: 'Tata Motors Limited',
    esgSector: '"Diversified"',
    esgMacroEconomicSector: 'Diversified',
    industry: 'Diversified',
    esgBasicIndustry: 'Diversified',
    esgRating: 78.55,
    esgCoreRating: 61.47,
    esgTransitionScore: 72.09,
    esgUpdatedTs: 1739276913437,
  },
];

export const comapanyDetails = [
  {
    ecmCompanyId: 1,
    ecmCompanyName: 'Tata Consultancy Services Limited',
    ecfsFinancialYear: '2024-2025',
    ecfsScore: '79.22',
    ecmMacroEconomicSector: 'IT',
    esnmScoreName: 'ESG Rating',
    description:
      'Tata Consultancy Services (TCS) is a multinational information technology services and consuling company headquartered in Mumbai, India. It falls under the inform ation Technology maçro-economic sector. TCS offers a wide range of services including IT services, digital andbusiness solutions, and consulting. The company is renowned for its expertise in software development, cloud computing, Al, and cybersecurity, serving clients across diverse industries globally.',
    ecfsUpdatedTs: '2024-07-24 00:00:00',
  },
  {
    ecmCompanyId: 1,
    ecmCompanyName: 'Tata Consultancy Services Limited',
    ecfsFinancialYear: '2024-2025',
    ecfsScore: '50.22',
    ecmMacroEconomicSector: 'IT',
    esnmScoreName: 'Core ESG Rating',
    description:
      'Tata Consultancy Services (TCS) is a multinational information technology services and consuling company headquartered in Mumbai, India. It falls under the inform ation Technology maçro-economic sector. TCS offers a wide range of services including IT services, digital andbusiness solutions, and consulting. The company is renowned for its expertise in software development, cloud computing, Al, and cybersecurity, serving clients across diverse industries globally.',
    ecfsUpdatedTs: '2024-07-21 00:00:00',
  },
  {
    ecmCompanyId: 1,
    ecmCompanyName: 'Tata Consultancy Services Limited',
    ecfsFinancialYear: '2024-2025',
    ecfsScore: '50.22',
    ecmMacroEconomicSector: 'IT',
    esnmScoreName: 'Transition Score',
    description:
      'Tata Consultancy Services (TCS) is a multinational information technology services and consuling company headquartered in Mumbai, India. It falls under the inform ation Technology maçro-economic sector. TCS offers a wide range of services including IT services, digital andbusiness solutions, and consulting. The company is renowned for its expertise in software development, cloud computing, Al, and cybersecurity, serving clients across diverse industries globally.',
    ecfsUpdatedTs: '2024-07-21 00:00:00',
  },
];

export const companyDetails = {
  companyId: 163,
  companyName: 'Tata Consultancy Services Limited',
  macroEconomicSector: 'Information Technology',
  sector: 'Information Technology',
  industry: 'IT - Software',
  basicIndustry: 'Computers - Software & Consulting',
  description:
    'Tata Consultancy Services (TCS) is a multinational information technology services and consuling company headquartered in Mumbai, India. It falls under the inform ation Technology maçro-economic sector. TCS offers a wide range of services including IT services, digital andbusiness solutions, and consulting. The company is renowned for its expertise in software development, cloud computing, Al, and cybersecurity, serving clients across diverse industries globally.',
  currentEsgRatings: 78.55,
  averageIndustryEsgRatings: 78.554,
  esgScore: 78.55,
  coreEsgScore: 61.47,
  transitionScore: 72.09,
  analystName: 'Suhas Shetty',
  updatedAt: '2025-02-11 18:00:55.016',
};

export const pillarDescriptionContent = {
  companyId: 1,
  pillarId: 1,
  description: `Pillar wise E, S & G scores-key drivers (including industry comparison of material parameters) 
  both quantitative and qualitative being considered for carrying out such assessment. Pillar wise E, S & G scores-key drivers (including industry comparison of material parameters) 
  both quantitative and qualitative being considered for carrying out such assessment. Pillar wise E, S & G scores-key drivers (including industry comparison of material parameters) 
  both quantitative and qualitative being considered for carrying out such assessment. Pillar wise E, S & G scores-key drivers (including industry comparison of material parameters) 
  both quantitative and qualitative being considered for carrying out such assessment.`,
  financialYear: '2023-2024',
};

export const govThemeData = {
  companyId: 1,
  companyName: 'HDFC Bank Limited',
  pillarId: 3,
  pillarName: 'Governance',
  esgthemeScoreResponse: [
    {
      themeId: 2,
      themeName: 'Audit and tax',
      themeScore: 1,
      themeScoreChange: 0,
      avgIndustryScore: 1.0,
      avgIndustryScoreChange: 0.0,
    },
    {
      themeId: 4,
      themeName: 'Board Composition',
      themeScore: 0.75,
      themeScoreChange: 0,
      avgIndustryScore: 0.75,
      avgIndustryScoreChange: 0.0,
    },
    {
      themeId: 5,
      themeName: 'Board Functioning',
      themeScore: 0.625,
      themeScoreChange: 0,
      avgIndustryScore: 0.63,
      avgIndustryScoreChange: 0.0,
    },
  ],
};

export const socialThemeData = {
  companyId: 1,
  companyName: 'HDFC Bank Limited',
  pillarId: 2,
  pillarName: 'Social',
  esgthemeScoreResponse: [
    {
      themeId: 2,
      themeName: 'Audit and tax',
      themeScore: 1,
      themeScoreChange: 0,
      avgIndustryScore: 1.0,
      avgIndustryScoreChange: 0.0,
    },
    {
      themeId: 4,
      themeName: 'Board Composition',
      themeScore: 0.75,
      themeScoreChange: 0,
      avgIndustryScore: 0.75,
      avgIndustryScoreChange: 0.0,
    },
    {
      themeId: 5,
      themeName: 'Board Functioning',
      themeScore: 0.625,
      themeScoreChange: 0,
      avgIndustryScore: 0.63,
      avgIndustryScoreChange: 0.0,
    },
  ],
};

export const envThemeData = {
  companyId: 1,
  companyName: 'HDFC Bank Limited',
  pillarId: 1,
  pillarName: 'Environment',
  esgthemeScoreResponse: [
    {
      themeId: 2,
      themeName: 'Audit and tax',
      themeScore: 1,
      themeScoreChange: 0,
      avgIndustryScore: 1.0,
      avgIndustryScoreChange: 0.0,
    },
    {
      themeId: 4,
      themeName: 'Board Composition',
      themeScore: 0.75,
      themeScoreChange: 0,
      avgIndustryScore: 0.75,
      avgIndustryScoreChange: 0.0,
    },
    {
      themeId: 5,
      themeName: 'Board Functioning',
      themeScore: 0.625,
      themeScoreChange: 0,
      avgIndustryScore: 0.63,
      avgIndustryScoreChange: 0.0,
    },
  ],
};

export const pillarScores = {
  companyId: 1,
  companyName: 'HDFC Bank Limited',
  environmentScore: 90.91,
  environmentScoreChange: 1.9285,
  environmentWeightage: 11.0,
  socialScore: 79.74,
  socialScoreChange: 2.9302,
  socialWeightage: 38.0,
  governanceScore: 72.2,
  governanceScoreChange: 6.1453,
  governanceWeightage: 51.0,
};

export const transitionScores = {
  companyId: 1,
  companyName: 'HDFC Bank Limited',
  environmentScore: 90.91,
  environmentScoreChange: 1.9285,
  environmentWeightage: 11.0,
  socialScore: 79.74,
  socialScoreChange: 2.9302,
  socialWeightage: 38.0,
  governanceScore: 72.2,
  governanceScoreChange: 6.1453,
  governanceWeightage: 51.0,
};

export const coreEsgRatings = {
  companyId: 1,
  companyName: 'HDFC Bank Limited',
  environmentScore: 90.91,
  environmentScoreChange: 1.9285,
  environmentWeightage: 11.0,
  socialScore: 79.74,
  socialScoreChange: 2.9302,
  socialWeightage: 38.0,
  governanceScore: 72.2,
  governanceScoreChange: 6.1453,
  governanceWeightage: 51.0,
};

export const coreTransitionScore = {
  companyId: 1,
  companyName: 'HDFC Bank Limited',
  scoreId: 4,
  scoreName: 'Core Transition Score',
  score: 2,
  scoreChange: -80.0,
  remark: 'nseit_akurhe:Test 2.nseit_akurhe:Test New:||',
};

export const coreCombinedScore = {
  companyId: 1,
  companyName: 'HDFC Bank Limited',
  scoreId: 6,
  scoreName: 'Combined Score',
  score: 2,
  scoreChange: -80.0,
  remark: 'nseit_akurhe:Test 2.nseit_akurhe:Test New:||',
};

export const controveryScore = {
  companyId: 1,
  companyName: 'HDFC Bank Limited',
  scoreId: 7,
  scoreName: 'Controversy Input',
  score: 2,
  scoreChange: -80.0,
  remark: 'nseit_akurhe:Test 2.nseit_akurhe:Test New:||',
};

export const sectorRatingCompanies = {
  lowestEsgCompany: {
    companyId: 269,
    companyName: 'DUMMY FOR MAX SCORE',
    scoreId: null,
    scoreName: null,
    score: 4,
    scoreChange: null,
    remark: null,
  },

  highestEsgCompany: {
    companyId: 263,
    companyName: '3M India Limited',
    scoreId: null,
    scoreName: null,
    score: 10,
    scoreChange: null,
    remark: null,
  },

  closestCompanies: [
    {
      companyId: 1,
      companyName: 'TTK Healthcare Limited',
      scoreId: null,
      scoreName: null,
      score: 5,
      scoreChange: null,
      remark: null,
    },
    {
      companyId: 2,
      companyName: 'ITC Ltd.',
      scoreId: null,
      scoreName: null,
      score: 6,
      scoreChange: null,
      remark: null,
    },
    {
      companyId: 3,
      companyName: 'ICICI Bank',
      scoreId: null,
      scoreName: null,
      score: 7,
      scoreChange: null,
      remark: null,
    },
  ],
};

export const performanceEvolution = {
  'Audit and tax': [
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
  ],
  'Board Composition': [
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
  ],
  'Board Functioning': [
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
  ],
  'Audit tax': [
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
    {
      dataPoint:
        'Does the company perform climate-related scenario analysis (based on TCFD Framework)',
      companyPerformance: 'Yes',
      bestPractice: 'Yes',
    },
  ],
};
