export const companies = [
  {
    ecmCompanyId: 1,
    ecmCompanyName: 'Reliance Industries Ltd',
    ecmCompanyEmail: 'reliance@company.com',
    ecmCreatedBy: 'SYSTEM',
    ecmCreatedTs: '2024-12-25 12:00:00',
    ecmUpdatedBy: null,
    ecmUpdatedTs: null,
    ecmCompanyFlag: 'Y',
  },
  {
    ecmCompanyId: 2,
    ecmCompanyName: 'Tata Consultancy Services Ltd.',
    ecmCompanyEmail: 'tcs@company.com',
    ecmCreatedBy: 'ADMIN',
    ecmCreatedTs: '2024-12-20 10:00:00',
    ecmUpdatedBy: 'USER_A',
    ecmUpdatedTs: '2024-12-22 15:00:00',
    ecmCompanyFlag: 'Y',
  },
  {
    ecmCompanyId: 3,
    ecmCompanyName: 'HDFC Bank Ltd.',
    ecmCompanyEmail: 'hdfc@company.com',
    ecmCreatedBy: 'SYSTEM',
    ecmCreatedTs: '2024-12-15 08:00:00',
    ecmUpdatedBy: null,
    ecmUpdatedTs: null,
    ecmCompanyFlag: 'N',
  },
  {
    ecmCompanyId: 4,
    ecmCompanyName: 'Bharti Airtel Ltd.',
    ecmCompanyEmail: 'airtel@company.com',
    ecmCreatedBy: 'ADMIN',
    ecmCreatedTs: '2024-11-25 11:30:00',
    ecmUpdatedBy: 'USER_B',
    ecmUpdatedTs: '2024-12-10 13:00:00',
    ecmCompanyFlag: 'Y',
  },
  {
    ecmCompanyId: 5,
    ecmCompanyName: 'ICICI Bank Ltd.',
    ecmCompanyEmail: 'icici@company.com',
    ecmCreatedBy: 'SYSTEM',
    ecmCreatedTs: '2024-10-20 16:45:00',
    ecmUpdatedBy: null,
    ecmUpdatedTs: null,
    ecmCompanyFlag: 'Y',
  },
  {
    ecmCompanyId: 6,
    ecmCompanyName: 'Infosys Ltd',
    ecmCompanyEmail: 'infosys@company.com',
    ecmCreatedBy: 'ADMIN',
    ecmCreatedTs: '2024-10-01 14:00:00',
    ecmUpdatedBy: 'USER_C',
    ecmUpdatedTs: '2024-11-10 09:00:00',
    ecmCompanyFlag: 'Y',
  },
  {
    ecmCompanyId: 7,
    ecmCompanyName: 'State Bank Of India',
    ecmCompanyEmail: 'sbi@company.com',
    ecmCreatedBy: 'SYSTEM',
    ecmCreatedTs: '2024-09-30 10:15:00',
    ecmUpdatedBy: null,
    ecmUpdatedTs: null,
    ecmCompanyFlag: 'N',
  },
  {
    ecmCompanyId: 8,
    ecmCompanyName: 'LIFE INSURANCE CORPORATION OF INDIA',
    ecmCompanyEmail: 'lic@company.com',
    ecmCreatedBy: 'SYSTEM',
    ecmCreatedTs: '2024-09-01 11:45:00',
    ecmUpdatedBy: null,
    ecmUpdatedTs: null,
    ecmCompanyFlag: 'Y',
  },
  {
    ecmCompanyId: 9,
    ecmCompanyName: 'Hindustan Unilever Ltd.',
    ecmCompanyEmail: 'hul@company.com',
    ecmCreatedBy: 'USER_D',
    ecmCreatedTs: '2024-08-15 12:30:00',
    ecmUpdatedBy: 'USER_E',
    ecmUpdatedTs: '2024-08-20 13:45:00',
    ecmCompanyFlag: 'Y',
  },
  {
    ecmCompanyId: 10,
    ecmCompanyName: 'ITC Ltd',
    ecmCompanyEmail: 'itc@company.com',
    ecmCreatedBy: 'SYSTEM',
    ecmCreatedTs: '2024-08-01 09:00:00',
    ecmUpdatedBy: null,
    ecmUpdatedTs: null,
    ecmCompanyFlag: 'N',
  },
  {
    ecmCompanyId: 11,
    ecmCompanyName: 'Larsen & Toubro Limited',
    ecmCompanyEmail: 'lt@company.com',
    ecmCreatedBy: 'USER_F',
    ecmCreatedTs: '2024-07-20 10:00:00',
    ecmUpdatedBy: 'USER_G',
    ecmUpdatedTs: '2024-07-25 16:00:00',
    ecmCompanyFlag: 'Y',
  },
  {
    ecmCompanyId: 12,
    ecmCompanyName: 'HCL Technologies Ltd',
    ecmCompanyEmail: 'hcl@company.com',
    ecmCreatedBy: 'SYSTEM',
    ecmCreatedTs: '2024-07-05 15:00:00',
    ecmUpdatedBy: null,
    ecmUpdatedTs: null,
    ecmCompanyFlag: 'Y',
  },
  {
    ecmCompanyId: 13,
    ecmCompanyName: 'Bajaj Finance Limited',
    ecmCompanyEmail: 'bajaj@company.com',
    ecmCreatedBy: 'ADMIN',
    ecmCreatedTs: '2024-06-20 12:45:00',
    ecmUpdatedBy: 'USER_H',
    ecmUpdatedTs: '2024-07-01 14:30:00',
    ecmCompanyFlag: 'Y',
  },
  {
    ecmCompanyId: 14,
    ecmCompanyName: 'Sun Pharmaceutical Industries Ltd.',
    ecmCompanyEmail: 'sunpharma@company.com',
    ecmCreatedBy: 'SYSTEM',
    ecmCreatedTs: '2024-06-10 10:30:00',
    ecmUpdatedBy: null,
    ecmUpdatedTs: null,
    ecmCompanyFlag: 'N',
  },
  {
    ecmCompanyId: 15,
    ecmCompanyName: 'Maruti Suzuki India Ltd.',
    ecmCompanyEmail: 'maruti@company.com',
    ecmCreatedBy: 'USER_I',
    ecmCreatedTs: '2024-05-25 16:00:00',
    ecmUpdatedBy: 'USER_J',
    ecmUpdatedTs: '2024-06-05 10:00:00',
    ecmCompanyFlag: 'Y',
  },
  {
    ecmCompanyId: 16,
    ecmCompanyName: 'NTPC Limited',
    ecmCompanyEmail: 'ntpc@company.com',
    ecmCreatedBy: 'SYSTEM',
    ecmCreatedTs: '2024-05-15 11:00:00',
    ecmUpdatedBy: null,
    ecmUpdatedTs: null,
    ecmCompanyFlag: 'N',
  },
  {
    ecmCompanyId: 17,
    ecmCompanyName: 'AXIS Bank Ltd.',
    ecmCompanyEmail: 'axis@company.com',
    ecmCreatedBy: 'ADMIN',
    ecmCreatedTs: '2024-05-01 14:30:00',
    ecmUpdatedBy: 'USER_K',
    ecmUpdatedTs: '2024-05-10 13:15:00',
    ecmCompanyFlag: 'Y',
  },
  {
    ecmCompanyId: 18,
    ecmCompanyName: 'Oil And Natural Gas Corporation Ltd',
    ecmCompanyEmail: 'ongc@company.com',
    ecmCreatedBy: 'USER_L',
    ecmCreatedTs: '2024-04-15 09:00:00',
    ecmUpdatedBy: null,
    ecmUpdatedTs: null,
    ecmCompanyFlag: 'Y',
  },
  {
    ecmCompanyId: 19,
    ecmCompanyName: 'Kotak Mahindra Bank Ltd.',
    ecmCompanyEmail: 'kotak@company.com',
    ecmCreatedBy: 'SYSTEM',
    ecmCreatedTs: '2024-03-30 12:30:00',
    ecmUpdatedBy: null,
    ecmUpdatedTs: null,
    ecmCompanyFlag: 'N',
  },
  {
    ecmCompanyId: 20,
    ecmCompanyName: 'Wipro Ltd.',
    ecmCompanyEmail: 'wipro@company.com',
    ecmCreatedBy: 'ADMIN',
    ecmCreatedTs: '2024-03-15 10:45:00',
    ecmUpdatedBy: 'USER_M',
    ecmUpdatedTs: '2024-03-25 14:15:00',
    ecmCompanyFlag: 'Y',
  },
];

export const comapanyDetails = [
  {
    ecmCompanyId: 1,
    ecmCompanyName: '3M INDIA LIMITED',
    ecfsFinancialYear: '2024-2025',
    ecfsScore: '79.22',
    esnmScoreName: 'ESG Rating',
    ecfsUpdatedTs: '2024-07-24 00:00:00',
  },
  {
    ecmCompanyId: 1,
    ecmCompanyName: '3M INDIA LIMITED',
    ecfsFinancialYear: '2024-2025',
    ecfsScore: '50.22',
    esnmScoreName: 'Core ESG Rating',
    ecfsUpdatedTs: '2024-07-21 00:00:00',
  },
];
