export const companiesRatings = [
  {
    companyId: 1,
    companyName: 'Reliance Industries Ltd',
    baseIndustry: 'Telecom and Communication',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
  },
  {
    companyId: 2,
    companyName: 'Tata Consultancy Services Ltd.',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
  {
    companyId: 3,
    companyName: 'HDFC Bank Ltd.',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
  {
    companyId: 4,
    companyName: 'Bharti Airtel Ltd.',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
  {
    companyId: 5,
    companyName: 'ICICI Bank Ltd.',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
  {
    companyId: 6,
    companyName: 'Infosys Ltd',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
  {
    companyId: 7,
    companyName: 'State Bank Of India',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
  {
    companyId: 8,
    companyName: 'LIFE INSURANCE CORPORATION OF INDIA',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
  {
    companyId: 9,
    companyName: 'Hindustan Unilever Ltd.',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
  {
    companyId: 10,
    companyName: 'ITC Ltd',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
  {
    companyId: 11,
    companyName: 'Larsen & Toubro Limited',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
  {
    companyId: 12,
    companyName: 'HCL Technologies Ltd',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
  {
    companyId: 13,
    companyName: 'Bajaj Finance Limited',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
  {
    companyId: 14,
    companyName: 'Sun Pharmaceutical Industries Ltd.',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
  {
    companyId: 15,
    companyName: 'Maruti Suzuki India Ltd.',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
  {
    companyId: 16,
    companyName: 'NTPC Limited',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
  {
    companyId: 17,
    companyName: 'AXIS Bank Ltd.',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
  {
    companyId: 18,
    companyName: 'Oil And Natural Gas Corporation Ltd',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
  {
    companyId: 19,
    companyName: 'Kotak Mahindra Bank Ltd.',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
  {
    companyId: 20,
    companyName: 'Wipro Ltd.',
    updatedAt: new Date(),
    esgRatings: 10,
    coreEsgRatings: 20,
    transitionScore: 30,
    createdAt: new Date(),
    baseIndustry: 'Telecom and Communication',
  },
];
